defaults:
  # configure coloured logging
  # NOTE: you need to have the colorlog plugin install (pip install hydra_colorlog)
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

Mixer:  # absolute path to directory with raw audio files from which features are computed
  raw_data_path: "Medley-solos-DB_small"
  # path where we write generated features and labels to
  pickle_path: "data/pickle/"
  # the type of data we want to generate. options: "training", "validation", "test"
  data_type: "test"
  # number of times we use each raw data file once
  num_epochs: 1
  num_instruments_mix: [1, 4]
  num_instruments: 8
  num_samples_per_file: 131072
  # options: CQT, STFT, MEL
  feature: "MEL"
  # options: "SPECTRUM" (use spectral data to compute envelope), "RMS" (RMS computed in time domain)
  envelope_type: "RMS"
  num_mels: 128
  f_min: 27.5
  f_max: 20000
  window: "hann"
  center: False
  num_bins_per_octave: 24
  num_octaves: 8
  Mix:
    dft_size: 2048
    hopsize: 1024
    num_frames: 14
    sr: 44100
    save_wav_data: True

train:
  # the directory with the pickle files containing features and labels (relative to repository root dir)
  dataset_dir: "data/pickle/"
  # the path where we load the most recent checkpoint from (relative to repository root dir)
  model_load_dir: null
  # the path we will save new models to (relative to hydra CWD)
  model_save_dir: "models/"
  # the path where tensorboard logs will be written to (relative to hydra CWD)
  tensorboard_dir: "logs/"
  # at least one of training_steps or training_epochs must be specified as >= 1
  training_steps: -1
  training_epochs: -1
  continue_training: True
  num_workers: 0
  batch_size: 32
  n_batches_per_average: 100
  model_checkpoint_interval: 1000
  gpu_index: 0
  use_batch_norm: True
  dropout_rate: 0.1

inference:
  # directory with audio files to run inference on
  # predictions will also be written there!
  audio_dir: ""
  # full path to model we want to use for prediction
  model_path: ""
  # path where predictions will be saved too
  predictions_dir: ""
  gpu_index: 0

# parameters for AdamW optimizer
optimizer:
  learning_rate: 0.001
  beta: [0.9, 0.999]
  weight_decay: 0.001

# parameters for ReduceLROnPlateau learning rate scheduler
scheduler:
  mode: "min"
  factor: 5.0
  patience: 8
  threshold: 0.0001
  min_lr: 0.00001
