defaults:
  # configure coloured logging
  # NOTE: you need to have the colorlog plugin install (pip install hydra_colorlog)
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
