defaults:
  # configure coloured logging
  # NOTE: you need to have the colorlog plugin install (pip install hydra_colorlog)
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

Mixer:
  data_path: "data/"
  dataset: "Medley-solos-DB"
  num_epochs: 1
  num_instruments: [1, 4]
  num_samples_per_file: 131072
  num_mixes_per_pickle: 1000
  type: "all"
  feature: "CQT"
  num_mels: 128
  f_min: 27.5
  f_max: 20000
  window: "hann"
  Mix:
    dft_size: 2048
    hopsize: 1024
    num_frames: 14
    sr: 44100
    # options: CQT, STFT, MEL
    feature: "CQT"

train:
  model_dir: "models/"
  training_steps: 1000
  continue_training: True
  num_workers: 2
  batch_size: 16

optimizer:
  learning_rate: 0.001
  beta: [0.9, 0.999]
  weight_decay: 0.001
