defaults:
  # configure coloured logging
  # NOTE: you need to have the colorlog plugin install (pip install hydra_colorlog)
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

Mixer:  # absolute path to directory with raw audio files from which features are computed
  raw_data_path: "Medley-solos-DB_small"
  # path where we write generated features and labels to
  pickle_path: "data/pickle/"
  # the type of data we want to generate. options: "training", "validation", "test"
  data_type: "test"
  # number of times we use each raw data file once
  num_epochs: 1
  num_instruments_mix: [1, 4]
  num_instruments: 8
  num_samples_per_file: 131072
  # options: CQT, STFT, MEL
  feature: "MEL"
  num_mels: 128
  f_min: 27.5
  f_max: 20000
  window: "hann"
  center: False
  num_bins_per_octave: 24
  num_octaves: 8
  Mix:
    dft_size: 2048
    hopsize: 1024
    num_frames: 14
    sr: 44100
    save_wav_data: True

train:
  # the directory with the pickle files containing features and labels (relative to repository root dir)
  dataset_dir: "data/pickle/"
  # the path where we load the most recent checkpoint from (relative to repository root dir)
  model_load_dir: null
  # the path we will save new models to (relative to hydra CWD)
  model_save_dir: "models/"
  # the path where tensorboard logs will be written to (relative to hydra CWD)
  tensorboard_dir: "logs/"
  training_steps: 1000
  continue_training: True
  num_workers: 2
  batch_size: 16
  n_batches_per_average: 100
  model_checkpoint_interval: 1000
  validation_interval: 10000
  gpu_index: 0

inference:
  gpu_index: 0

optimizer:
  learning_rate: 0.001
  beta: [0.9, 0.999]
  weight_decay: 0.001
